"""Application-wide constants for the ANPR pipeline."""

from __future__ import annotations

import os
from pathlib import Path

PROJECT_ROOT = Path(os.getenv("ANPR_PROJECT_ROOT", Path.cwd())).resolve()

DEFAULT_COCO_MODEL = Path("modelos") / "yolov8n.pt"
DEFAULT_PLATE_MODEL = Path("modelos") / "best.pt"
DEFAULT_RUNS_DIR = Path("runs") / "predict"
DEFAULT_SOURCE_VIDEO = Path("Videos_input") / "Test1.mp4"
DEFAULT_SOURCE_IMAGE = Path("Imagens_input") / "Test1.jpg"
DEFAULT_LOG_DIR = Path("runs") / "logs"

IMAGE_EXTENSIONS = {".jpg", ".jpeg", ".png", ".bmp", ".tif", ".tiff", ".webp"}
VEHICLE_CLASSES = (2, 3, 5, 7)
PLATE_PATTERNS = ("LLLDDDD", "LLLDLDD")

DEFAULT_IMG_SIZE = 640
DEFAULT_VEHICLE_CONF = 0.60
DEFAULT_VEHICLE_IOU = 0.70
DEFAULT_VEHICLE_MIN_AREA_RATIO = 0.002
DEFAULT_PLATE_CONF = 0.01
DEFAULT_PLATE_RECALL_CONF = 0.003
DEFAULT_PLATE_IOU = 0.50
DEFAULT_MAX_PLATES = 6

DEFAULT_TRACK_IOU = 0.30
DEFAULT_TRACK_MIN_HITS = 3
DEFAULT_TRACK_MAX_AGE = 15
DEFAULT_PLATE_VOTE_WINDOW = 10
DEFAULT_PLATE_SWITCH_DOMINANCE_FRAMES = 3
DEFAULT_DEBUGGER_WINDOW_FRAMES = 30
DEFAULT_PLATE_MIN_OCCURRENCES = 2
DEFAULT_PLATE_MIN_SCORE = 65.0
DEFAULT_OCR_INTERVAL_FRAMES = 1

DEFAULT_ASSOCIATION_THRESHOLD = 0.34
DEFAULT_ASSOCIATION_WEIGHTS = (0.5, 0.3, 0.2)
DEFAULT_ROI_CACHE_TTL = 2

DEFAULT_PLATE_TEXT_CONF_MIN = 70.0
DEFAULT_PLATE_TEXT_CONF_MAX = 100.0
DEFAULT_PLATE_BBOX_SMOOTH_ENABLED = True
DEFAULT_PLATE_BBOX_SMOOTH_ALPHA = 0.35
